"""Add foreign

Revision ID: 913bb14d847b
Revises: 3a634bdd7fb1
Create Date: 2025-04-15 10:53:53.535559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913bb14d847b'
down_revision: Union[str, None] = '3a634bdd7fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'user_id')
    # ### end Alembic commands ###
